# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ce3eb182522d94d242cb21581894163225408e112bdef6107ca3b25159251ec507f29659c3278e0a9e7e3c29f290070aa5f7e6782dc08b40ad85a2ead0e061

test:
  secret_key_base: d7c5f50f2c8ac0b9bbfc0e8a81c1558f0671278747e0188dfa3fcfc44e16b48a07b684c58e68bb3783ed44d6fea2b81f92088899e0e9b9fd0c0ed1884b244be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
